name: deployment

permissions:
  contents: write

on: push


jobs:
  npm-build:
    name: npm-build job
    runs-on: ubuntu-latest

    steps:
    - name: checkout data
      uses: actions/checkout@v4

    - name: install dependences
      run:
        npm install
        npm run build
        
    - name: deploymentc
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
